name: "validate"
description: "Validates the Github Action deployment"
inputs:
  tag-name:
    description: "The name of the tag associated with the release"
    required: true
runs:
  using: "node16"
  main: "index.js"
